# Server properties
server:
  port: 8100

# Application metadata
info:
  app:
    environment: DEV
    name: ${spring.application.name}
    description: Identity Service - Local Instance

# Spring properties
spring:
  application:
    name: auth-identity
  profiles:
    active: dev
  config:
    import:
      - optional:configserver:discovery://config-server
      - optional:file:../env/dev.properties
  datasource:
    url: ${DB_URL}
    driverClassName: ${DB_DRIVER_CLASS}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: ${DB_DIALECT}
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.add.type.headers]": false
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        "[spring.deserializer.value.delegate.class]": org.springframework.kafka.support.serializer.JsonDeserializer
        "[spring.json.trusted.packages]": "com.mariuszilinskas.streamix.*"
        "[spring.json.value.default.type]": "com.mariuszilinskas.streamix.auth.identity.event.UserRegisteredEvent"
  rabbitmq:
    host: ${RMQ_HOST}
    port: ${RMQ_PORT}
    username: ${RMQ_USERNAME}
    password: ${RMQ_PASSWORD}

# Service discovery properties
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE}
  instance:
    preferIpAddress: true

# Messaging properties
kafka:
  topics:
    user-registered: ${KAFKA_USER_REGISTERED_TOPIC}
    user-registered-dlt: ${KAFKA_USER_REGISTERED_DLT_TOPIC}
  groups:
    identity-registration: ${KAFKA_IDENTITY_REGISTRATION_GROUP}

rabbitmq:
  exchange: ${RMQ_EXCHANGE}
  queues:
    reset-passcode: ${RMQ_RESET_PASSCODE_Q}
    delete-user-data: ${RMQ_DELETE_USER_DATA_Q}
  routing-keys:
    verify-account: ${RMQ_VERIFY_ACCOUNT_RK}
    platform-emails: ${RMQ_PLATFORM_EMAILS_RK}
    reset-passcode: ${RMQ_RESET_PASSCODE_RK}
    delete-user-data: ${RMQ_DELETE_USER_DATA_RK}

# Security properties
cryptography:
  provider: local
  encryption-key: ${CRYPTOGRAPHY_ENCRYPTION_KEY}

# Management and observability properties
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, refresh, prometheus
  endpoint:
    health:
      show-details: always
  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}
      service.namespace: streamix
      deployment.environment: ${spring.profiles.active}
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_TRACES_ENDPOINT}
  otlp:
    metrics:
      export:
        url: ${OTEL_METRICS_ENDPOINT}

# Logging properties
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.mariuszilinskas.streamix: DEBUG
